/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class audio_faac_FaacCodec */

#ifndef _Included_audio_faac_FaacCodec
#define _Included_audio_faac_FaacCodec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     audio_faac_FaacCodec
 * Method:    init
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_audio_faac_FaacCodec_init
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     audio_faac_FaacCodec
 * Method:    encode
 * Signature: ([BI)Laudio/faac/EncodedData;
 */
JNIEXPORT jobject JNICALL Java_audio_faac_FaacCodec_encode
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     audio_faac_FaacCodec
 * Method:    uninit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_audio_faac_FaacCodec_uninit
  (JNIEnv *, jclass);

/*
 * Class:     audio_faac_FaacCodec
 * Method:    setDebug
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_audio_faac_FaacCodec_setDebug
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
